/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import java.util.Observable;
import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author Admin
 */
public class BudgetView extends javax.swing.JPanel {

    /**
     * Creates new form BudgetView2
     */
    public BudgetView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTotal = new javax.swing.JLabel();
        lblPercentage = new javax.swing.JLabel();
        lblMonthly = new javax.swing.JLabel();
        lblCategory = new javax.swing.JLabel();
        lblRent = new javax.swing.JLabel();
        lblGroceries = new javax.swing.JLabel();
        lblClothing = new javax.swing.JLabel();
        lblTransportation = new javax.swing.JLabel();
        lblEducation = new javax.swing.JLabel();
        lblEntertainment = new javax.swing.JLabel();
        lblSavings = new javax.swing.JLabel();
        lblOther = new javax.swing.JLabel();
        spinRentPer = new javax.swing.JSpinner();
        spinClothingPer = new javax.swing.JSpinner();
        spinGroceriesPer = new javax.swing.JSpinner();
        spinEducationPer = new javax.swing.JSpinner();
        spinTransportationPer = new javax.swing.JSpinner();
        spinEntertainmentPer = new javax.swing.JSpinner();
        spinSavingsPer = new javax.swing.JSpinner();
        spinOtherPer = new javax.swing.JSpinner();
        txtTotalPer = new javax.swing.JTextField();
        txtGroceriesVal = new javax.swing.JTextField();
        txtRentVal = new javax.swing.JTextField();
        txtTransportationVal = new javax.swing.JTextField();
        txtClothingVal = new javax.swing.JTextField();
        txtEntertainmentVal = new javax.swing.JTextField();
        txtEducationVal = new javax.swing.JTextField();
        txtSavingsVal = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        txtOtherVal = new javax.swing.JTextField();
        txtTotalVal = new javax.swing.JTextField();

        lblTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTotal.setText("Total Income");

        lblPercentage.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPercentage.setText("Percentage of Income");

        lblMonthly.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMonthly.setText("Monthly Value");

        lblCategory.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCategory.setText("Category of Expenses");

        lblRent.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblRent.setText("Rent/Utilities");

        lblGroceries.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblGroceries.setText("Groceries");

        lblClothing.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblClothing.setText("Clothing");

        lblTransportation.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTransportation.setText("Transportation/Car");

        lblEducation.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEducation.setText("Education");

        lblEntertainment.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEntertainment.setText("Entertainment");

        lblSavings.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSavings.setText("Savings");

        lblOther.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblOther.setText("Other");

        spinRentPer.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 100.0d, 1.0d));
        spinRentPer.addChangeListener(new Changes());
        spinRentPer.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinRentPerStateChanged(evt);
            }
        });

        spinClothingPer.addChangeListener(new Changes());
        spinClothingPer.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 100.0d, 1.0d));

        spinGroceriesPer.addChangeListener(new Changes());
        spinGroceriesPer.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 100.0d, 1.0d));

        spinEducationPer.addChangeListener(new Changes());
        spinEducationPer.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 100.0d, 1.0d));

        spinTransportationPer.addChangeListener(new Changes());
        spinTransportationPer.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 100.0d, 1.0d));

        spinEntertainmentPer.addChangeListener(new Changes());
        spinEntertainmentPer.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 100.0d, 1.0d));

        spinSavingsPer.addChangeListener(new Changes());
        spinSavingsPer.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 100.0d, 1.0d));

        spinOtherPer.addChangeListener(new Changes());
        spinOtherPer.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 100.0d, 1.0d));

        txtTotalPer.setEditable(false);
        txtTotalPer.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txtGroceriesVal.setEditable(false);
        txtGroceriesVal.setFocusable(false);

        txtRentVal.setEditable(false);
        txtRentVal.setFocusable(false);

        txtTransportationVal.setEditable(false);
        txtTransportationVal.setFocusable(false);

        txtClothingVal.setEditable(false);
        txtClothingVal.setFocusable(false);

        txtEntertainmentVal.setEditable(false);
        txtEntertainmentVal.setFocusable(false);

        txtEducationVal.setEditable(false);
        txtEducationVal.setFocusable(false);

        txtSavingsVal.setEditable(false);
        txtSavingsVal.setFocusable(false);

        btnUpdate.setText("Update");

        btnClear.setText("Clear");

        txtOtherVal.setEditable(false);
        txtOtherVal.setFocusable(false);

        txtTotalVal.setEditable(false);
        txtTotalVal.setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblClothing)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblSavings)
                                .addGap(222, 222, 222)
                                .addComponent(spinSavingsPer))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblEntertainment)
                                .addGap(182, 182, 182)
                                .addComponent(spinEntertainmentPer))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblTransportation)
                                .addGap(153, 153, 153)
                                .addComponent(spinTransportationPer))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblEducation)
                                .addGap(208, 208, 208)
                                .addComponent(spinEducationPer))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblGroceries)
                                .addGap(213, 213, 213)
                                .addComponent(spinGroceriesPer))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCategory)
                                    .addComponent(lblRent))
                                .addGap(98, 98, 98)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(spinClothingPer)
                                    .addComponent(spinRentPer)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblPercentage)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblOther)
                                    .addComponent(lblTotal))
                                .addGap(164, 164, 164)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(spinOtherPer)
                                    .addComponent(txtTotalPer))))
                        .addGap(114, 114, 114)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtRentVal, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtGroceriesVal, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTransportationVal, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtClothingVal, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtEducationVal, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtEntertainmentVal, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSavingsVal, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtOtherVal, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTotalVal, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblMonthly))
                .addGap(39, 39, 39))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140)
                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(230, 230, 230))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPercentage)
                    .addComponent(lblCategory)
                    .addComponent(lblMonthly))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRent)
                            .addComponent(spinRentPer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGroceries)
                            .addComponent(spinGroceriesPer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblClothing)
                            .addComponent(spinClothingPer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTransportation)
                            .addComponent(spinTransportationPer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEducation)
                            .addComponent(spinEducationPer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEntertainment)
                            .addComponent(spinEntertainmentPer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSavings)
                            .addComponent(spinSavingsPer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblOther)
                            .addComponent(spinOtherPer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTotal)
                            .addComponent(txtTotalPer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtRentVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtGroceriesVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtClothingVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTransportationVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtEducationVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtEntertainmentVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtSavingsVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtOtherVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTotalVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnClear))
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void spinRentPerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinRentPerStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_spinRentPerStateChanged

    public void addController(ActionListener controller){
        // Adding event handlers to the menu and nav bar items
        btnClear.addActionListener(controller);	
        btnClear.setActionCommand("btnClear"); 

        btnUpdate.addActionListener(controller);	
        btnUpdate.setActionCommand("btnUpdate");     
        
    } 

    public double getTotalPer() {
        double totalPer = (double)spinRentPer.getValue() + (double)spinGroceriesPer.getValue() + (double)spinClothingPer.getValue() + (double)spinTransportationPer.getValue() +
                            (double)spinEducationPer.getValue() + (double)spinEntertainmentPer.getValue() + (double)spinSavingsPer.getValue() + (double)spinOtherPer.getValue(); 
        return totalPer;             
    }
    
    public double getRentPercent() {
        return (double)spinRentPer.getValue();
    }
    
    public double getGroceryPercent() {
        return (double)spinGroceriesPer.getValue(); 
    }
    
    public double getClothingPercent() {
        return (double)spinClothingPer.getValue();
    }
    
    public double getTransportationPercent() {
        return (double)spinTransportationPer.getValue();
    }
    
    public double getEducationPercent() {
        return (double)spinEducationPer.getValue();
    }
    
    public double getEntertainmentPercent(){ 
        return (double)spinEntertainmentPer.getValue();
    }
    
    public double getSavingsPercent() {
        return (double)spinSavingsPer.getValue();
    }
    
    public double getOtherPercent() {
        return (double)spinOtherPer.getValue();
    }
    
    public void showMessage(String type) {
        if (type == "incorrectTotalPer") {
            JOptionPane.showMessageDialog(null, "Error - All budget percentage fields must add up to 100%", "Error Message", JOptionPane.ERROR_MESSAGE);
        }
        else if (type == "budgetEntrySuccessful") {
            JOptionPane.showMessageDialog(null, "Budget targets updated successfully.", "Budget Update Successful", JOptionPane.INFORMATION_MESSAGE);                        
        }
    }

    // Allows for dynamic updating of values based on percentage and total income 
    // Handler kept in view because updates are only concerned with display and do not affect the model layer
    
    private class Changes implements ChangeListener{
        double totalValPer,rentVal,groceriesVal,clothingVal,transportationVal,educationVal,entertainmentVal,savingsVal,otherVal;
        public void stateChanged(ChangeEvent e) {
            if (!(txtTotalVal.getText().isEmpty())) {
                if(e.getSource()==spinRentPer){
                    totalValPer = getTotalPer();
                    if(totalValPer > 100.0){
                        JOptionPane.showMessageDialog(null, "Error - All budget percentage fields must add up to 100%!", "Error Message", JOptionPane.ERROR_MESSAGE);
                        spinRentPer.setValue(0.0);
                    }else{                   
                        txtTotalPer.setText(totalValPer+"");
                        rentVal = (double)spinRentPer.getValue()/100*Double.parseDouble(txtTotalVal.getText());
                        txtRentVal.setText(rentVal+"");
                    }
                }else if(e.getSource()==spinGroceriesPer){
                    totalValPer = getTotalPer();
                    if(totalValPer > 100.0){
                        JOptionPane.showMessageDialog(null, "Error - All budget percentage fields must add up to 100%!", "Error Message", JOptionPane.ERROR_MESSAGE);
                        spinGroceriesPer.setValue(0.0);
                    }else{
                        txtTotalPer.setText(totalValPer+"");
                        groceriesVal = (double)spinGroceriesPer.getValue()/100*Double.parseDouble(txtTotalVal.getText());
                        txtGroceriesVal.setText(groceriesVal+"");
                    }
                }else if(e.getSource()==spinClothingPer){
                    totalValPer = getTotalPer();
                    if(totalValPer > 100.0){
                        JOptionPane.showMessageDialog(null, "Error - All budget percentage fields must add up to 100%!", "Error Message", JOptionPane.ERROR_MESSAGE);
                        spinClothingPer.setValue(0.0);
                    }else{
                        txtTotalPer.setText(totalValPer+"");
                        clothingVal = (double)spinClothingPer.getValue()/100*Double.parseDouble(txtTotalVal.getText());
                        txtClothingVal.setText(clothingVal+"");
                    }
                }else if(e.getSource()==spinTransportationPer){
                    totalValPer = getTotalPer();
                    if(totalValPer > 100.0){
                        JOptionPane.showMessageDialog(null, "Error - All budget percentage fields must add up to 100%!", "Error Message", JOptionPane.ERROR_MESSAGE);
                        spinTransportationPer.setValue(0.0);
                    }else{
                        txtTotalPer.setText(totalValPer+"");
                        transportationVal = (double)spinTransportationPer.getValue()/100*Double.parseDouble(txtTotalVal.getText());
                        txtTransportationVal.setText(transportationVal+"");
                    }
                }else if(e.getSource()==spinEducationPer){
                    totalValPer = getTotalPer();
                    if(totalValPer > 100.0){
                        JOptionPane.showMessageDialog(null, "Error - All budget percentage fields must add up to 100%!", "Error Message", JOptionPane.ERROR_MESSAGE);
                        spinEducationPer.setValue(0.0);
                    }else{
                        txtTotalPer.setText(totalValPer+"");
                        educationVal = (double)spinEducationPer.getValue()/100*Double.parseDouble(txtTotalVal.getText());
                        txtEducationVal.setText(educationVal+"");
                    }
                }else if(e.getSource()==spinEntertainmentPer){
                    totalValPer = getTotalPer();
                    if(totalValPer > 100.0){
                        JOptionPane.showMessageDialog(null, "Error - All budget percentage fields must add up to 100%!", "Error Message", JOptionPane.ERROR_MESSAGE);
                        spinEntertainmentPer.setValue(0.0);
                    }else{
                        txtTotalPer.setText(totalValPer+"");
                        entertainmentVal = (double)spinEntertainmentPer.getValue()/100*Double.parseDouble(txtTotalVal.getText());
                        txtEntertainmentVal.setText(entertainmentVal+"");
                    }
                }else if(e.getSource()==spinSavingsPer){
                    totalValPer = getTotalPer();
                    if(totalValPer > 100.0){
                        JOptionPane.showMessageDialog(null, "Error - All budget percentage fields must add up to 100%!", "Error Message", JOptionPane.ERROR_MESSAGE);
                        spinSavingsPer.setValue(0.0);
                    }else{
                        txtTotalPer.setText(totalValPer+"");
                        savingsVal = (double)spinSavingsPer.getValue()/100*Double.parseDouble(txtTotalVal.getText());
                        txtSavingsVal.setText(savingsVal+"");
                    }
                }else if(e.getSource()==spinOtherPer){
                    totalValPer = getTotalPer(); 
                    if(totalValPer > 100.0){
                        JOptionPane.showMessageDialog(null, "Error - All budget percentage fields must add up to 100%!", "Error Message", JOptionPane.ERROR_MESSAGE);
                        spinOtherPer.setValue(0.0);
                    }else{
                        txtTotalPer.setText(totalValPer+"");
                        otherVal = (double)spinOtherPer.getValue()/100*Double.parseDouble(txtTotalVal.getText());
                        txtOtherVal.setText(otherVal+"");
                    }
                }
            }
        }
    }
 
    
    public void clearValues() {
        spinRentPer.setValue(0.0);
        txtRentVal.setText("0.0");
        spinGroceriesPer.setValue(0.0);
        txtClothingVal.setText("0.0");
        spinClothingPer.setValue(0.0);
        txtGroceriesVal.setText("0.0"); 
        spinTransportationPer.setValue(0.0);
        txtTransportationVal.setText("0.0"); 
        spinEducationPer.setValue(0.0);
        txtEducationVal.setText("0.0"); 
        spinEntertainmentPer.setValue(0.0);
        txtEntertainmentVal.setText("0.0"); 
        spinSavingsPer.setValue(0.0);
        txtSavingsVal.setText("0.0"); 
        spinOtherPer.setValue(0.0);
        txtOtherVal.setText("0.0"); 
        txtTotalPer.setText("0.0"); 
        //txtTotalVal.setText("0.0"); 
    }
    
    
    // Updates the values based on the user's income entries
    public void setValues(double totalIncome, double rent, double groceries, double clothing, double transportation, double education, double entertainment, double savings, double other) {
            txtTotalVal.setText(Double.toString(totalIncome)); 
            txtRentVal.setText(Double.toString((rent / 100) * totalIncome)); 
            txtGroceriesVal.setText(Double.toString((groceries / 100) * totalIncome)); 
            txtClothingVal.setText(Double.toString((clothing / 100) * totalIncome)); 
            txtTransportationVal.setText(Double.toString((transportation / 100) * totalIncome)); 
            txtEducationVal.setText(Double.toString((education / 100) * totalIncome)); 
            txtEntertainmentVal.setText(Double.toString((entertainment / 100) * totalIncome)); 
            txtSavingsVal.setText(Double.toString((savings / 100) * totalIncome)); 
            txtOtherVal.setText(Double.toString((other / 100) * totalIncome)); 
        }
    
     
    
    public void setBudgetPercentages(double rent, double groceries, double clothing, double transportation, double education, double entertainment, double savings, double other) {
            spinRentPer.setValue(rent); 
            spinGroceriesPer.setValue(groceries); 
            spinClothingPer.setValue(clothing);
            spinTransportationPer.setValue(transportation);
            spinEducationPer.setValue(education); 
            spinSavingsPer.setValue(savings);
            spinEntertainmentPer.setValue(entertainment);
            spinOtherPer.setValue(other);
            double total = 100;
            txtTotalPer.setText(Double.toString(total)); 
        }
    
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblClothing;
    private javax.swing.JLabel lblEducation;
    private javax.swing.JLabel lblEntertainment;
    private javax.swing.JLabel lblGroceries;
    private javax.swing.JLabel lblMonthly;
    private javax.swing.JLabel lblOther;
    private javax.swing.JLabel lblPercentage;
    private javax.swing.JLabel lblRent;
    private javax.swing.JLabel lblSavings;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTransportation;
    private javax.swing.JSpinner spinClothingPer;
    private javax.swing.JSpinner spinEducationPer;
    private javax.swing.JSpinner spinEntertainmentPer;
    private javax.swing.JSpinner spinGroceriesPer;
    private javax.swing.JSpinner spinOtherPer;
    private javax.swing.JSpinner spinRentPer;
    private javax.swing.JSpinner spinSavingsPer;
    private javax.swing.JSpinner spinTransportationPer;
    private javax.swing.JTextField txtClothingVal;
    private javax.swing.JTextField txtEducationVal;
    private javax.swing.JTextField txtEntertainmentVal;
    private javax.swing.JTextField txtGroceriesVal;
    private javax.swing.JTextField txtOtherVal;
    private javax.swing.JTextField txtRentVal;
    private javax.swing.JTextField txtSavingsVal;
    private javax.swing.JTextField txtTotalPer;
    private javax.swing.JTextField txtTotalVal;
    private javax.swing.JTextField txtTransportationVal;
    // End of variables declaration//GEN-END:variables
}
