/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import java.util.Observable;
import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author Admin
 */
public class BudgetView extends javax.swing.JPanel {

    /**
     * Creates new form BudgetView2
     */
    public BudgetView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTotal = new javax.swing.JLabel();
        lblPercentage = new javax.swing.JLabel();
        lblMonthly = new javax.swing.JLabel();
        lblCategory = new javax.swing.JLabel();
        lblRent = new javax.swing.JLabel();
        lblGroceries = new javax.swing.JLabel();
        lblClothing = new javax.swing.JLabel();
        lblTransportation = new javax.swing.JLabel();
        lblEducation = new javax.swing.JLabel();
        lblEntertainment = new javax.swing.JLabel();
        lblSavings = new javax.swing.JLabel();
        lblOther = new javax.swing.JLabel();
        spinRentPer = new javax.swing.JSpinner();
        spinClothingPer = new javax.swing.JSpinner();
        spinGroceriesPer = new javax.swing.JSpinner();
        spinEducationPer = new javax.swing.JSpinner();
        spinTransportationPer = new javax.swing.JSpinner();
        spinEntertainmentPer = new javax.swing.JSpinner();
        spinSavingsPer = new javax.swing.JSpinner();
        spinOtherPer = new javax.swing.JSpinner();
        txtTotalPer = new javax.swing.JTextField();
        txtGroceriesVal = new javax.swing.JTextField();
        txtRentVal = new javax.swing.JTextField();
        txtTransportationVal = new javax.swing.JTextField();
        txtClothingVal = new javax.swing.JTextField();
        txtEntertainmentVal = new javax.swing.JTextField();
        txtEducationVal = new javax.swing.JTextField();
        txtSavingsVal = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        txtOtherVal = new javax.swing.JTextField();
        txtTotalVal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        lblTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblTotal.setText("Total Income");
        add(lblTotal);
        lblTotal.setBounds(33, 373, 140, 22);

        lblPercentage.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblPercentage.setForeground(new java.awt.Color(255, 255, 255));
        lblPercentage.setText("Percentage of Income");
        add(lblPercentage);
        lblPercentage.setBounds(302, 13, 210, 22);

        lblMonthly.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblMonthly.setForeground(new java.awt.Color(255, 255, 255));
        lblMonthly.setText("Monthly Value");
        add(lblMonthly);
        lblMonthly.setBounds(589, 13, 150, 22);

        lblCategory.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCategory.setForeground(new java.awt.Color(255, 255, 255));
        lblCategory.setText("Category of Expenses");
        add(lblCategory);
        lblCategory.setBounds(33, 13, 210, 22);

        lblRent.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblRent.setForeground(new java.awt.Color(255, 255, 255));
        lblRent.setText("Rent/Utilities");
        add(lblRent);
        lblRent.setBounds(33, 55, 110, 17);

        lblGroceries.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblGroceries.setForeground(new java.awt.Color(255, 255, 255));
        lblGroceries.setText("Groceries");
        add(lblGroceries);
        lblGroceries.setBounds(33, 95, 90, 17);

        lblClothing.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblClothing.setForeground(new java.awt.Color(255, 255, 255));
        lblClothing.setText("Clothing");
        add(lblClothing);
        lblClothing.setBounds(33, 135, 90, 17);

        lblTransportation.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTransportation.setForeground(new java.awt.Color(255, 255, 255));
        lblTransportation.setText("Transportation/Car");
        add(lblTransportation);
        lblTransportation.setBounds(33, 175, 150, 17);

        lblEducation.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEducation.setForeground(new java.awt.Color(255, 255, 255));
        lblEducation.setText("Education");
        add(lblEducation);
        lblEducation.setBounds(33, 215, 100, 17);

        lblEntertainment.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEntertainment.setForeground(new java.awt.Color(255, 255, 255));
        lblEntertainment.setText("Entertainment");
        add(lblEntertainment);
        lblEntertainment.setBounds(33, 255, 120, 17);

        lblSavings.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSavings.setForeground(new java.awt.Color(255, 255, 255));
        lblSavings.setText("Savings");
        add(lblSavings);
        lblSavings.setBounds(33, 295, 80, 17);

        lblOther.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblOther.setForeground(new java.awt.Color(255, 255, 255));
        lblOther.setText("Other");
        add(lblOther);
        lblOther.setBounds(33, 335, 70, 17);

        spinRentPer.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 100.0d, 1.0d));
        spinRentPer.addChangeListener(new Changes());
        spinRentPer.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinRentPerStateChanged(evt);
            }
        });
        add(spinRentPer);
        spinRentPer.setBounds(302, 53, 173, 22);

        spinClothingPer.addChangeListener(new Changes());
        spinClothingPer.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 100.0d, 1.0d));
        add(spinClothingPer);
        spinClothingPer.setBounds(302, 133, 173, 22);

        spinGroceriesPer.addChangeListener(new Changes());
        spinGroceriesPer.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 100.0d, 1.0d));
        add(spinGroceriesPer);
        spinGroceriesPer.setBounds(302, 93, 173, 22);

        spinEducationPer.addChangeListener(new Changes());
        spinEducationPer.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 100.0d, 1.0d));
        add(spinEducationPer);
        spinEducationPer.setBounds(302, 213, 173, 22);

        spinTransportationPer.addChangeListener(new Changes());
        spinTransportationPer.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 100.0d, 1.0d));
        add(spinTransportationPer);
        spinTransportationPer.setBounds(302, 173, 173, 22);

        spinEntertainmentPer.addChangeListener(new Changes());
        spinEntertainmentPer.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 100.0d, 1.0d));
        add(spinEntertainmentPer);
        spinEntertainmentPer.setBounds(302, 253, 173, 22);

        spinSavingsPer.addChangeListener(new Changes());
        spinSavingsPer.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 100.0d, 1.0d));
        add(spinSavingsPer);
        spinSavingsPer.setBounds(302, 293, 173, 22);

        spinOtherPer.addChangeListener(new Changes());
        spinOtherPer.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 100.0d, 1.0d));
        add(spinOtherPer);
        spinOtherPer.setBounds(302, 333, 173, 22);

        txtTotalPer.setEditable(false);
        txtTotalPer.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        add(txtTotalPer);
        txtTotalPer.setBounds(302, 375, 173, 22);

        txtGroceriesVal.setEditable(false);
        txtGroceriesVal.setFocusable(false);
        add(txtGroceriesVal);
        txtGroceriesVal.setBounds(589, 93, 172, 22);

        txtRentVal.setEditable(false);
        txtRentVal.setFocusable(false);
        add(txtRentVal);
        txtRentVal.setBounds(589, 53, 172, 22);

        txtTransportationVal.setEditable(false);
        txtTransportationVal.setFocusable(false);
        add(txtTransportationVal);
        txtTransportationVal.setBounds(589, 173, 172, 22);

        txtClothingVal.setEditable(false);
        txtClothingVal.setFocusable(false);
        add(txtClothingVal);
        txtClothingVal.setBounds(589, 133, 172, 22);

        txtEntertainmentVal.setEditable(false);
        txtEntertainmentVal.setFocusable(false);
        add(txtEntertainmentVal);
        txtEntertainmentVal.setBounds(589, 253, 172, 22);

        txtEducationVal.setEditable(false);
        txtEducationVal.setFocusable(false);
        add(txtEducationVal);
        txtEducationVal.setBounds(589, 213, 172, 22);

        txtSavingsVal.setEditable(false);
        txtSavingsVal.setFocusable(false);
        add(txtSavingsVal);
        txtSavingsVal.setBounds(589, 293, 172, 22);

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUpdate.setText("Update");
        add(btnUpdate);
        btnUpdate.setBounds(230, 400, 100, 25);

        btnClear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnClear.setText("Clear");
        add(btnClear);
        btnClear.setBounds(470, 400, 100, 25);

        txtOtherVal.setEditable(false);
        txtOtherVal.setFocusable(false);
        add(txtOtherVal);
        txtOtherVal.setBounds(589, 333, 172, 22);

        txtTotalVal.setEditable(false);
        txtTotalVal.setFocusable(false);
        add(txtTotalVal);
        txtTotalVal.setBounds(589, 373, 172, 22);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background2.jpg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, -10, 900, 560);
    }// </editor-fold>//GEN-END:initComponents

    private void spinRentPerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinRentPerStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_spinRentPerStateChanged

    public void addController(ActionListener controller){
        // Adding event handlers to the menu and nav bar items
        btnClear.addActionListener(controller);	
        btnClear.setActionCommand("btnClear"); 

        btnUpdate.addActionListener(controller);	
        btnUpdate.setActionCommand("btnUpdate");     
        
    } 

    public double getTotalPer() {
        double totalPer = (double)spinRentPer.getValue() + (double)spinGroceriesPer.getValue() + (double)spinClothingPer.getValue() + (double)spinTransportationPer.getValue() +
                            (double)spinEducationPer.getValue() + (double)spinEntertainmentPer.getValue() + (double)spinSavingsPer.getValue() + (double)spinOtherPer.getValue(); 
        return totalPer;             
    }
    
    public double getRentPercent() {
        return (double)spinRentPer.getValue();
    }
    
    public double getGroceryPercent() {
        return (double)spinGroceriesPer.getValue(); 
    }
    
    public double getClothingPercent() {
        return (double)spinClothingPer.getValue();
    }
    
    public double getTransportationPercent() {
        return (double)spinTransportationPer.getValue();
    }
    
    public double getEducationPercent() {
        return (double)spinEducationPer.getValue();
    }
    
    public double getEntertainmentPercent(){ 
        return (double)spinEntertainmentPer.getValue();
    }
    
    public double getSavingsPercent() {
        return (double)spinSavingsPer.getValue();
    }
    
    public double getOtherPercent() {
        return (double)spinOtherPer.getValue();
    }
    
    public void showMessage(String type) {
        if (type == "incorrectTotalPer") {
            JOptionPane.showMessageDialog(null, "Error - All budget percentage fields must add up to 100%", "Error Message", JOptionPane.ERROR_MESSAGE);
        }
        else if (type == "budgetEntrySuccessful") {
            JOptionPane.showMessageDialog(null, "Budget targets updated successfully.", "Budget Update Successful", JOptionPane.INFORMATION_MESSAGE);                        
        }
    }

    // Allows for dynamic updating of values based on percentage and total income 
    // Handler kept in view because updates are only concerned with display and do not affect the model layer
    
    private class Changes implements ChangeListener{
        double totalValPer,rentVal,groceriesVal,clothingVal,transportationVal,educationVal,entertainmentVal,savingsVal,otherVal;
        public void stateChanged(ChangeEvent e) {
            if (!(txtTotalVal.getText().isEmpty())) {
                if(e.getSource()==spinRentPer){
                    totalValPer = getTotalPer();
                    if(totalValPer > 100.0){
                        JOptionPane.showMessageDialog(null, "Error - All budget percentage fields must add up to 100%!", "Error Message", JOptionPane.ERROR_MESSAGE);
                        spinRentPer.setValue(0.0);
                    }else{                   
                        txtTotalPer.setText(totalValPer+"");
                        rentVal = (double)spinRentPer.getValue()/100*Double.parseDouble(txtTotalVal.getText());
                        txtRentVal.setText(rentVal+"");
                    }
                }else if(e.getSource()==spinGroceriesPer){
                    totalValPer = getTotalPer();
                    if(totalValPer > 100.0){
                        JOptionPane.showMessageDialog(null, "Error - All budget percentage fields must add up to 100%!", "Error Message", JOptionPane.ERROR_MESSAGE);
                        spinGroceriesPer.setValue(0.0);
                    }else{
                        txtTotalPer.setText(totalValPer+"");
                        groceriesVal = (double)spinGroceriesPer.getValue()/100*Double.parseDouble(txtTotalVal.getText());
                        txtGroceriesVal.setText(groceriesVal+"");
                    }
                }else if(e.getSource()==spinClothingPer){
                    totalValPer = getTotalPer();
                    if(totalValPer > 100.0){
                        JOptionPane.showMessageDialog(null, "Error - All budget percentage fields must add up to 100%!", "Error Message", JOptionPane.ERROR_MESSAGE);
                        spinClothingPer.setValue(0.0);
                    }else{
                        txtTotalPer.setText(totalValPer+"");
                        clothingVal = (double)spinClothingPer.getValue()/100*Double.parseDouble(txtTotalVal.getText());
                        txtClothingVal.setText(clothingVal+"");
                    }
                }else if(e.getSource()==spinTransportationPer){
                    totalValPer = getTotalPer();
                    if(totalValPer > 100.0){
                        JOptionPane.showMessageDialog(null, "Error - All budget percentage fields must add up to 100%!", "Error Message", JOptionPane.ERROR_MESSAGE);
                        spinTransportationPer.setValue(0.0);
                    }else{
                        txtTotalPer.setText(totalValPer+"");
                        transportationVal = (double)spinTransportationPer.getValue()/100*Double.parseDouble(txtTotalVal.getText());
                        txtTransportationVal.setText(transportationVal+"");
                    }
                }else if(e.getSource()==spinEducationPer){
                    totalValPer = getTotalPer();
                    if(totalValPer > 100.0){
                        JOptionPane.showMessageDialog(null, "Error - All budget percentage fields must add up to 100%!", "Error Message", JOptionPane.ERROR_MESSAGE);
                        spinEducationPer.setValue(0.0);
                    }else{
                        txtTotalPer.setText(totalValPer+"");
                        educationVal = (double)spinEducationPer.getValue()/100*Double.parseDouble(txtTotalVal.getText());
                        txtEducationVal.setText(educationVal+"");
                    }
                }else if(e.getSource()==spinEntertainmentPer){
                    totalValPer = getTotalPer();
                    if(totalValPer > 100.0){
                        JOptionPane.showMessageDialog(null, "Error - All budget percentage fields must add up to 100%!", "Error Message", JOptionPane.ERROR_MESSAGE);
                        spinEntertainmentPer.setValue(0.0);
                    }else{
                        txtTotalPer.setText(totalValPer+"");
                        entertainmentVal = (double)spinEntertainmentPer.getValue()/100*Double.parseDouble(txtTotalVal.getText());
                        txtEntertainmentVal.setText(entertainmentVal+"");
                    }
                }else if(e.getSource()==spinSavingsPer){
                    totalValPer = getTotalPer();
                    if(totalValPer > 100.0){
                        JOptionPane.showMessageDialog(null, "Error - All budget percentage fields must add up to 100%!", "Error Message", JOptionPane.ERROR_MESSAGE);
                        spinSavingsPer.setValue(0.0);
                    }else{
                        txtTotalPer.setText(totalValPer+"");
                        savingsVal = (double)spinSavingsPer.getValue()/100*Double.parseDouble(txtTotalVal.getText());
                        txtSavingsVal.setText(savingsVal+"");
                    }
                }else if(e.getSource()==spinOtherPer){
                    totalValPer = getTotalPer(); 
                    if(totalValPer > 100.0){
                        JOptionPane.showMessageDialog(null, "Error - All budget percentage fields must add up to 100%!", "Error Message", JOptionPane.ERROR_MESSAGE);
                        spinOtherPer.setValue(0.0);
                    }else{
                        txtTotalPer.setText(totalValPer+"");
                        otherVal = (double)spinOtherPer.getValue()/100*Double.parseDouble(txtTotalVal.getText());
                        txtOtherVal.setText(otherVal+"");
                    }
                }
            }
        }
    }
 
    
    public void clearValues() {
        spinRentPer.setValue(0.0);
        txtRentVal.setText("0.0");
        spinGroceriesPer.setValue(0.0);
        txtClothingVal.setText("0.0");
        spinClothingPer.setValue(0.0);
        txtGroceriesVal.setText("0.0"); 
        spinTransportationPer.setValue(0.0);
        txtTransportationVal.setText("0.0"); 
        spinEducationPer.setValue(0.0);
        txtEducationVal.setText("0.0"); 
        spinEntertainmentPer.setValue(0.0);
        txtEntertainmentVal.setText("0.0"); 
        spinSavingsPer.setValue(0.0);
        txtSavingsVal.setText("0.0"); 
        spinOtherPer.setValue(0.0);
        txtOtherVal.setText("0.0"); 
        txtTotalPer.setText("0.0"); 
        //txtTotalVal.setText("0.0"); 
    }
    
    
    // Updates the values based on the user's income entries
    public void setValues(double totalIncome, double rent, double groceries, double clothing, double transportation, double education, double entertainment, double savings, double other) {
            txtTotalVal.setText(Double.toString(totalIncome)); 
            txtRentVal.setText(Double.toString((rent / 100) * totalIncome)); 
            txtGroceriesVal.setText(Double.toString((groceries / 100) * totalIncome)); 
            txtClothingVal.setText(Double.toString((clothing / 100) * totalIncome)); 
            txtTransportationVal.setText(Double.toString((transportation / 100) * totalIncome)); 
            txtEducationVal.setText(Double.toString((education / 100) * totalIncome)); 
            txtEntertainmentVal.setText(Double.toString((entertainment / 100) * totalIncome)); 
            txtSavingsVal.setText(Double.toString((savings / 100) * totalIncome)); 
            txtOtherVal.setText(Double.toString((other / 100) * totalIncome)); 
        }
    
     
    
    public void setBudgetPercentages(double rent, double groceries, double clothing, double transportation, double education, double entertainment, double savings, double other) {
            spinRentPer.setValue(rent); 
            spinGroceriesPer.setValue(groceries); 
            spinClothingPer.setValue(clothing);
            spinTransportationPer.setValue(transportation);
            spinEducationPer.setValue(education); 
            spinSavingsPer.setValue(savings);
            spinEntertainmentPer.setValue(entertainment);
            spinOtherPer.setValue(other);
            double total = 100;
            txtTotalPer.setText(Double.toString(total)); 
        }
    
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblClothing;
    private javax.swing.JLabel lblEducation;
    private javax.swing.JLabel lblEntertainment;
    private javax.swing.JLabel lblGroceries;
    private javax.swing.JLabel lblMonthly;
    private javax.swing.JLabel lblOther;
    private javax.swing.JLabel lblPercentage;
    private javax.swing.JLabel lblRent;
    private javax.swing.JLabel lblSavings;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTransportation;
    private javax.swing.JSpinner spinClothingPer;
    private javax.swing.JSpinner spinEducationPer;
    private javax.swing.JSpinner spinEntertainmentPer;
    private javax.swing.JSpinner spinGroceriesPer;
    private javax.swing.JSpinner spinOtherPer;
    private javax.swing.JSpinner spinRentPer;
    private javax.swing.JSpinner spinSavingsPer;
    private javax.swing.JSpinner spinTransportationPer;
    private javax.swing.JTextField txtClothingVal;
    private javax.swing.JTextField txtEducationVal;
    private javax.swing.JTextField txtEntertainmentVal;
    private javax.swing.JTextField txtGroceriesVal;
    private javax.swing.JTextField txtOtherVal;
    private javax.swing.JTextField txtRentVal;
    private javax.swing.JTextField txtSavingsVal;
    private javax.swing.JTextField txtTotalPer;
    private javax.swing.JTextField txtTotalVal;
    private javax.swing.JTextField txtTransportationVal;
    // End of variables declaration//GEN-END:variables
}
