/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.ExpenseStatus;

/**
 *
 * @author Admin
 */
public class ExpensesView extends javax.swing.JPanel {

    /**
     * Creates new form ExpensesView3
     */
    public ExpensesView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboCategory = new javax.swing.JComboBox();
        btnDisplay = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnAddExpense = new javax.swing.JButton();
        lblGenerateReport = new javax.swing.JLabel();
        lblCategory = new javax.swing.JLabel();
        lblMonth = new javax.swing.JLabel();
        comboMonth = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        comboCategory.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboCategory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "View All", "Rent/Utilities", "Groceries", "Clothing", "Transportation/Car", "Education", "Entertainment", "Other" }));
        comboCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCategoryActionPerformed(evt);
            }
        });
        add(comboCategory);
        comboCategory.setBounds(474, 222, 250, 23);

        btnDisplay.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDisplay.setText("View Expenses");
        add(btnDisplay);
        btnDisplay.setBounds(50, 380, 170, 31);

        btnClear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnClear.setText("Clear");
        add(btnClear);
        btnClear.setBounds(320, 380, 160, 31);

        btnAddExpense.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAddExpense.setText("Add Expense");
        add(btnAddExpense);
        btnAddExpense.setBounds(580, 380, 170, 31);

        lblGenerateReport.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblGenerateReport.setText("Generate an Expense Report");
        add(lblGenerateReport);
        lblGenerateReport.setBounds(33, 13, 280, 22);

        lblCategory.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/categoryIcon.png"))); // NOI18N
        lblCategory.setText("    Select a Category");
        lblCategory.setToolTipText("");
        add(lblCategory);
        lblCategory.setBounds(33, 217, 220, 32);

        lblMonth.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblMonth.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/monthIcon.png"))); // NOI18N
        lblMonth.setText("    Select a Month");
        lblMonth.setToolTipText("");
        add(lblMonth);
        lblMonth.setBounds(33, 97, 200, 32);

        comboMonth.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboMonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "View All", "January", "February", "March", "April", "May", "June", "July", "August", "September", "November", "December" }));
        comboMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMonthActionPerformed(evt);
            }
        });
        add(comboMonth);
        comboMonth.setBounds(474, 102, 250, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blueBackground.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1);
        jLabel1.setBounds(-10, -10, 850, 470);
    }// </editor-fold>//GEN-END:initComponents

    private void comboCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboCategoryActionPerformed

    private void comboMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboMonthActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddExpense;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDisplay;
    private javax.swing.JComboBox comboCategory;
    private javax.swing.JComboBox comboMonth;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblGenerateReport;
    private javax.swing.JLabel lblMonth;
    // End of variables declaration//GEN-END:variables


    public void addController(ActionListener controller){
        // Adding event handlers to the menu and nav bar items
        btnDisplay.addActionListener(controller);	
        btnDisplay.setActionCommand("btnDisplay"); 

        btnAddExpense.addActionListener(controller);	
        btnAddExpense.setActionCommand("btnAddExpense");     
        
        btnClear.addActionListener(controller);
        btnClear.setActionCommand("btnClear"); 
    } 
    
    public String getCategory() {
        String category = comboCategory.getSelectedItem().toString();
        return category;
    }
    
    public String getMonth() {
        String month = getShortMonth(comboMonth.getSelectedItem().toString());
        return month;
    }

    public String getShortMonth(String month){
        String shortMonth="";
        switch(month){
            case "January":
                shortMonth = "Jan";
                break;
            case "February":
                shortMonth = "Feb";
                break;
            case "March":
                shortMonth = "Mar";
                break;
            case "April":
                shortMonth = "Apr";
                break;
            case "May":
                shortMonth = "May";
                break;
            case "June":
                shortMonth ="Jun";
                break;
            case "July":
                shortMonth = "Jul";
                break;
            case "August":
                shortMonth = "Aug";
                break;
            case "September":
                shortMonth = "Sep";
                break;
            case "October":
                shortMonth = "Oct";
                break;
            case "November":
                shortMonth = "Nov";
                break;
            case "December":
                shortMonth = "Dec";
                break;
            default:
                shortMonth = "View All";
                break;
        }
        return shortMonth;
    }
    
    public void displayExpenses(String category,String month,Object[][] rowData) {
        DisplayExpensesView displayExpensesPopUp = new DisplayExpensesView(category,month,rowData); 
        controller.DisplayExpensesController displayExpensesController = new controller.DisplayExpensesController();
        displayExpensesController.addView(displayExpensesPopUp);
        displayExpensesPopUp.addController(displayExpensesController);
        ExpenseStatus expenseModel = new ExpenseStatus(); 
        displayExpensesController.addModel(expenseModel);
    }
    
    public void displayNoExpenses() {
        JOptionPane.showMessageDialog(null, "There are no expense entries for the selected period/category.", "No Expenses", JOptionPane.ERROR_MESSAGE);
    }
    
    
    public void displayAddExpense() {
        AddExpenseView addExpensePopUp = new AddExpenseView(); 
        controller.AddExpenseController addExpenseController = new controller.AddExpenseController();
        addExpenseController.addView(addExpensePopUp);
        addExpensePopUp.addController(addExpenseController);
        ExpenseStatus expenseModel = new ExpenseStatus(); 
        addExpenseController.addModel(expenseModel);
        
    }

    public void clearValues() {
        comboMonth.setSelectedItem("View All"); 
        comboCategory.setSelectedItem("View All"); 
    }
    

    

}
