/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import java.util.Observable;
import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author Admin
 */
public class IncomeView extends javax.swing.JPanel {

    /**
     * Creates new form IncomeView2
     */
    public IncomeView() {
        initComponents();
    }
    
    public void addController(ActionListener controller){
        // Adding event handlers to the menu and nav bar items
        btnClear.addActionListener(controller);	
        btnClear.setActionCommand("btnClear"); 

        btnUpdate.addActionListener(controller);	
        btnUpdate.setActionCommand("btnUpdate");     
        
    } 
    
    public double getTotal() {
        double totalVal = (double)spinSalary.getValue() + (double)spinInvestments.getValue() + (double)spinBonus.getValue() + (double)spinTax.getValue(); 
        return totalVal; 
    }
    
    public double getSalary() {
        double salary = (Double)spinSalary.getValue();
        return salary;
    }
    
    public double getInvestments() {
        double investments = (Double)spinInvestments.getValue(); 
        return investments;
    }
    
    public double getTax() {
        double tax = (Double)spinTax.getValue();
        return tax;
        
    }
    
    public double getBonus() {
        double bonus = (Double)spinBonus.getValue();
        return bonus;
    }
    
    public void setTotal(double total) {
        String totalString = Double.toString(total); 
        txtTotal.setText(totalString); 
    }
    
    public void displayUpdateMessage() {
        JOptionPane.showMessageDialog(null, "Income updated successfully.", "Income Update Successful", JOptionPane.INFORMATION_MESSAGE);                    
    }


    // Allows for dynamic updating of value for total income 
    // Handler kept in view because updates are only concerned with display and do not affect the model layer
    private class Changes implements ChangeListener{
            double totalVal;
            public void stateChanged(ChangeEvent e) {
                if(e.getSource() == spinSalary){
                    totalVal = (double)spinSalary.getValue() + (double)spinInvestments.getValue() + (double)spinBonus.getValue() + (double)spinTax.getValue();
                    txtTotal.setText(totalVal+"");
                }else if(e.getSource() == spinInvestments){
                    totalVal = (double)spinSalary.getValue() + (double)spinInvestments.getValue() + (double)spinBonus.getValue() + (double)spinTax.getValue();
                    txtTotal.setText(totalVal+"");
                }else if(e.getSource() == spinBonus){
                    totalVal = (double)spinSalary.getValue() + (double)spinInvestments.getValue() + (double)spinBonus.getValue() + (double)spinTax.getValue();
                    txtTotal.setText(totalVal+"");
                }else if(e.getSource() == spinTax){
                    totalVal = (double)spinSalary.getValue() + (double)spinInvestments.getValue() + (double)spinBonus.getValue() + (double)spinTax.getValue();
                    txtTotal.setText(totalVal+"");
                }            
            }
        }
 
    // Fills in the fields based on user's information as soon as they navigate to the page
    public void setValues(double salary, double investments, double bonus, double tax, double total) {
        spinSalary.setValue(salary); 
        spinInvestments.setValue(investments); 
        spinBonus.setValue(bonus); 
        spinTax.setValue(tax); 
        txtTotal.setText(Double.toString(total)); 
    }
    
   
    public void clearValues() {
        spinSalary.setValue(0.0); 
        spinInvestments.setValue(0.0);
        spinBonus.setValue(0.0); 
        spinTax.setValue(0.0);
        txtTotal.setText(""); 
    }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPercentage = new javax.swing.JLabel();
        lblCategory = new javax.swing.JLabel();
        lblSalary = new javax.swing.JLabel();
        lblInvestments = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblBonus = new javax.swing.JLabel();
        lblGrants = new javax.swing.JLabel();
        spinSalary = new javax.swing.JSpinner();
        spinBonus = new javax.swing.JSpinner();
        spinTax = new javax.swing.JSpinner();
        spinInvestments = new javax.swing.JSpinner();
        txtTotal = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        lblPercentage.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPercentage.setText("Monthly Value");

        lblCategory.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCategory.setText("Category of Earnings");

        lblSalary.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSalary.setText("Salary");

        lblInvestments.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblInvestments.setText("Investments");

        lblTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTotal.setText("Total Income");

        lblBonus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblBonus.setText("Bonus");

        lblGrants.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblGrants.setText("Grants/Tax Credits");

        spinSalary.addChangeListener(new Changes());
        spinSalary.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), Double.valueOf(0.0d), null, Double.valueOf(1.0d)));

        spinBonus.addChangeListener(new Changes());
        spinBonus.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), Double.valueOf(0.0d), null, Double.valueOf(1.0d)));

        spinTax.addChangeListener(new Changes());
        spinTax.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), Double.valueOf(0.0d), null, Double.valueOf(1.0d)));

        spinInvestments.addChangeListener(new Changes());
        spinInvestments.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), Double.valueOf(0.0d), null, Double.valueOf(1.0d)));

        txtTotal.setEditable(false);
        txtTotal.setFocusable(false);

        btnUpdate.setText("Update");

        btnClear.setText("Clear");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblSalary)
                                .addComponent(lblBonus)
                                .addComponent(lblTotal))
                            .addGap(34, 34, 34))
                        .addComponent(lblGrants))
                    .addComponent(lblInvestments)
                    .addComponent(lblCategory))
                .addGap(292, 292, 292)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spinBonus)
                    .addComponent(spinTax, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTotal)
                    .addComponent(spinInvestments)
                    .addComponent(spinSalary)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(lblPercentage, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)))
                .addGap(39, 39, 39))
            .addGroup(layout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126)
                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategory)
                    .addComponent(lblPercentage))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSalary)
                    .addComponent(spinSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInvestments)
                    .addComponent(spinInvestments, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBonus)
                    .addComponent(spinBonus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGrants)
                    .addComponent(spinTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnClear))
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel lblBonus;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblGrants;
    private javax.swing.JLabel lblInvestments;
    private javax.swing.JLabel lblPercentage;
    private javax.swing.JLabel lblSalary;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JSpinner spinBonus;
    private javax.swing.JSpinner spinInvestments;
    private javax.swing.JSpinner spinSalary;
    private javax.swing.JSpinner spinTax;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
