/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Admin
 */
public class NavBarView extends javax.swing.JPanel {

    /**
     * Creates new form NavBarView2
     */
    public NavBarView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBudget = new javax.swing.JButton();
        btnIncome = new javax.swing.JButton();
        btnExpenses = new javax.swing.JButton();
        btnReport = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        btnBudget.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBudget.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/budget.png"))); // NOI18N
        btnBudget.setText("Budget");
        btnBudget.setToolTipText("View or set your budget parameters");
        add(btnBudget);

        btnIncome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnIncome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/income.png"))); // NOI18N
        btnIncome.setText("Income");
        btnIncome.setToolTipText("View or edit your income details");
        add(btnIncome);

        btnExpenses.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnExpenses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/expenses.png"))); // NOI18N
        btnExpenses.setText("Expenses");
        btnExpenses.setToolTipText("View or enter your expenses");
        add(btnExpenses);

        btnReport.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/report.png"))); // NOI18N
        btnReport.setText("Report");
        btnReport.setToolTipText("Set-up and generate a report");
        add(btnReport);

        btnLogout.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setToolTipText("End your session");
        add(btnLogout);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton btnBudget;
    protected javax.swing.JButton btnExpenses;
    protected javax.swing.JButton btnIncome;
    protected javax.swing.JButton btnLogout;
    protected javax.swing.JButton btnReport;
    // End of variables declaration//GEN-END:variables
}
